# Generated by Django 4.2.20 on 2025-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
