# Generated by Django 4.2.20 on 2025-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
